export const allTopics = [
  'Array',
  'String',
  'Hash Table',
  'Dynamic Programming',
  'Math',
  'Sorting',
  'Greedy',
  'Depth-First Search',
  'Binary Search',
  'Database',
  'Breadth-First Search',
  'Tree',
  'Matrix',
  'Two Pointers',
  'Binary Tree',
  'Bit Manipulation',
  'Heap (Priority Queue)',
  'Stack',
  'Graph',
  'Prefix Sum',
  'Simulation',
  'Design',
  'Counting',
  'Backtracking',
  'Sliding Window',
  'Union Find',
  'Linked List',
  'Ordered Set',
  'Monotonic Stack',
  'Enumeration',
  'Trie',
  'Recursion',
  'Divide and Conquer',
  'Bitmask',
  'Queue',
  'Binary Search Tree',
  'Segment Tree',
  'Memoization',
  'Geometry',
  'Topological Sort',
  'Binary Indexed Tree',
  'Hash Function',
  'Game Theory',
  'Shortest Path',
  'Combinatorics',
  'Interactive',
  'String Matching',
  'Data Stream',
  'Rolling Hash',
  'Brainteaser',
  'Randomized',
  'Monotonic Queue',
  'Merge Sort',
  'Iterator',
  'Concurrency',
  'Doubly-Linked List',
  'Probability and Statistics',
  'Quickselect',
  'Bucket Sort',
  'Suffix Array',
  'Minimum Spanning Tree',
  'Counting Sort',
  'Shell',
  'Line Sweep',
  'Reservoir Sampling',
  'Strongly Connected Component',
  'Eulerian Circuit',
  'Radix Sort',
  'Rejection Sampling',
  'Biconnected Component'
];
